apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  namespace: oteltest-local
  labels:
    app: webserver-php-fpm
spec:
  selector:
    app: webserver-php-fpm
  ports:
  - name: fastcgi
    port: 9000
    targetPort: 9000
  - name: http
    port: 8080
    targetPort: 8080
